name: kfold_amy_plaque1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.3.2=h166bdaf_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - atk-1.0=2.36.0=h3371d22_4
  - backcall=0.2.0=pyh9f0ad1d_0
  - backoff=2.2.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - blas=1.0=mkl
  - blessed=1.19.1=pyhe4f9e05_2
  - blosc=1.21.1=hd32f23e_0
  - boost-cpp=1.74.0=h312852a_4
  - boto3=1.34.90=pyhd8ed1ab_0
  - botocore=1.34.91=pyge38_1234567_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.0=py39hd667e15_1
  - cfitsio=3.470=hb418390_7
  - charls=2.2.0=h9c3ff4c_0
  - charset-normalizer=2.0.4=pyhd8ed1ab_0
  - click=8.0.4=py39hf3d152e_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - croniter=1.4.1=pyhd8ed1ab_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=10.2.89=h713d32c_10
  - curl=7.82.0=h7f8727e_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.32=py39h6a678d5_0
  - cytoolz=0.11.0=py39h3811e60_3
  - dask-core=2022.5.0=pyhd8ed1ab_0
  - dateutils=0.6.12=py_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h5a03fae_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - deepdiff=6.2.2=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.3.2=hca11adc_0
  - fftw=3.3.10=nompi_h77c792f_102
  - filelock=3.9.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - freexl=1.0.6=h7f98852_0
  - fribidi=1.0.10=h36c2ea0_0
  - future=0.18.2=pyhd8ed1ab_6
  - g-ir-build-tools=1.68.0=py39haf67bb6_2
  - g-ir-host-tools=1.68.0=hc194b35_2
  - gcc=11.2.0=h702ea55_10
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=h4f31c25_6
  - gettext=0.21.0=hf68c758_0
  - ghostscript=9.54.0=h27087fc_2
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.18=pyhd8ed1ab_0
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.68.0=py39hcb793ab_2
  - grad-cam=1.3.9=pyhd8ed1ab_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.49.0=h85b4f2f_0
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - gstreamer-orc=0.4.32=h7f98852_1
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - h11=0.14.0=pyhd8ed1ab_0
  - harfbuzz=2.9.1=h83ec7ef_1
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - huggingface_hub=0.17.3=pyhd8ed1ab_0
  - icu=68.1=h58526e2_0
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2021.7.30=py39h44211f0_1
  - imageio=2.34.0=pyh4b66e23_0
  - imagemagick=7.1.0_8=pl5321hb118871_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - inquirer=3.1.4=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.10.0=pyh41d4057_0
  - itsdangerous=2.2.0=pyhd8ed1ab_0
  - jasper=1.900.1=h07fcdf6_1006
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=py39h06a4308_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - json-c=0.15=h98cffda_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.12.0=py39hf3d152e_0
  - jxrlib=1.1=h7f98852_2
  - kealib=1.4.14=hcc255d8_2
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39hf939315_1
  - krb5=1.19.2=h3790be6_4
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcurl=7.82.0=h0b77cf5_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libexif=0.6.21=h7f98852_0
  - libffi=3.3=h58526e2_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h6ad9fb6_0
  - libgdal=3.2.2=h358be1b_9
  - libgfortran-ng=11.2.0=h69a702a_16
  - libgfortran5=11.2.0=h5c6108e_16
  - libgirepository=1.68.0=h7771c88_2
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.2.0=h1234567_1
  - libgsf=1.14.47=h88be47d_4
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f98852_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libmatio=1.5.21=h9e294dc_0
  - libnetcdf=4.8.1=nompi_hcd642e3_100
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.7.4.75=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.8.0.2=0
  - libogg=1.3.5=h27cfd23_1
  - libopencv=4.5.3=py39h70bf20d_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.16.0=h780b84a_0
  - librsvg=2.52.2=hc3c00ef_0
  - librttopo=1.1.0=h1185371_6
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialite=5.0.1=h8694cbe_6
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_16
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.3.0=hf544144_1
  - libtool=2.4.6=h9c3ff4c_1008
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libvips=8.11.4=h0632ac6_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_1
  - libzopfli=1.0.3=h9c3ff4c_0
  - lightning=2.1.2=pyhd8ed1ab_0
  - lightning-cloud=0.5.68=pyhd8ed1ab_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - magma=2.5.4=hfead8bd_4
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib=3.5.2=py39hf3d152e_1
  - matplotlib-base=3.5.2=py39h700656a_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py39h06a4308_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nccl=2.12.12.1=h1a5f58c_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.7.1=pyhd8ed1ab_1
  - ninja=1.10.2=h4bd325d_1
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.3=py39h807cd23_0
  - numpy=1.22.3=py39he7a7128_0
  - numpy-base=1.22.3=py39hf524024_0
  - opencv=4.5.3=py39hf3d152e_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openslide=3.4.1=h978ee9a_4
  - openssl=1.1.1o=h166bdaf_0
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.4=py39h6a678d5_0
  - pango=1.48.10=hb8ff022_1
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pcre=8.45=h9c3ff4c_0
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py39h22f2fdc_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - plotly=5.13.0=pyhd8ed1ab_0
  - poppler=21.09.0=ha39eefc_3
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=13.3=h2510834_0
  - pretrainedmodels=0.7.4=pyhd8ed1ab_2
  - proj=8.0.1=h277dcde_0
  - promise=2.3=py39hf3d152e_7
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.0=py39hb9d737c_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.5.3=py39hef51801_1
  - pycocotools=2.0.4=py39hce5d2b2_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyfiglet=0.8.post1=py_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pyparsing=3.0.4=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.7=h49503c6_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python_abi=3.9=3_cp39
  - pytorch=2.0.0=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_3
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=pyhd8ed1ab_0
  - pywavelets=1.3.0=py39hd257fcd_1
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=19.0.2=py39hb69f2a1_2
  - qt=5.12.9=hda022c4_4
  - qudida=0.0.4=pyhd8ed1ab_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.0=pyhd8ed1ab_1
  - rich=13.7.1=pyhd8ed1ab_0
  - s3transfer=0.10.1=pyhd8ed1ab_0
  - safetensors=0.4.2=py39ha89cbab_0
  - scikit-image=0.19.2=py39hde0f152_0
  - scipy=1.9.3=py39h14f4228_1
  - sentry-sdk=1.9.0=pyhd8ed1ab_0
  - setproctitle=1.2.2=py39hb9d737c_2
  - setuptools=61.2.0=py39hf3d152e_3
  - shortuuid=1.0.10=pyha770c72_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - smmap=4.0.0=pyhd8ed1ab_1
  - snappy=1.1.9=hbd366e4_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - sympy=1.11.1=py39h06a4308_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tenacity=8.0.1=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2020.10.1=py_0
  - tiledb=2.3.4=he87e0bf_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - torchaudio=2.0.0=py39_cu117
  - torchtriton=2.0.0=py39
  - torchvision=0.15.0=py39_cu117
  - tornado=6.1=py39hb9d737c_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - ttach=0.0.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing_extensions=4.1.1=pyha770c72_0
  - tzcode=2022a=h166bdaf_0
  - tzdata=2022a=h191b570_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wandb=0.13.5=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xerces-c=3.2.3=h9d8b166_3
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=0.5.5=h9c3ff4c_8
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - albumentations==1.3.0
      - altair==5.1.2
      - annotated-types==0.6.0
      - anyio==3.7.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - centerline==1.1.0
      - click-plugins==1.1.1
      - cligj==0.7.2
      - config==0.5.1
      - cupy-cuda11x==13.0.0
      - efficientnet-pytorch==0.7.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.1.3
      - fastapi==0.104.0
      - fastjsonschema==2.17.1
      - fastrlock==0.8.2
      - ffmpy==0.3.1
      - fiona==1.9.6
      - frozenlist==1.4.0
      - fsspec==2023.9.2
      - geojson==3.0.1
      - gradio==3.49.0
      - gradio-client==0.6.1
      - grpcio==1.62.2
      - httpcore==0.18.0
      - httpx==0.25.0
      - huggingface-hub==0.18.0
      - imgaug==0.4.0
      - importlib-resources==6.1.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.18.0
      - jsonschema-specifications==2023.6.1
      - lightning-utilities==0.9.0
      - llvmlite==0.41.1
      - lmdb==1.4.1
      - markdown==3.6
      - multidict==6.0.4
      - nbformat==5.9.1
      - numba==0.58.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.7.0.68
      - openpyxl==3.1.2
      - openslide-python==1.2.0
      - orjson==3.9.9
      - patsy==0.5.6
      - protobuf==3.16.0
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pydub==0.25.1
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.7
      - pyvips==2.2.1
      - referencing==0.29.1
      - rpds-py==0.8.10
      - scikit-learn==1.1.3
      - seaborn==0.12.2
      - segmentation-models-pytorch==0.3.2
      - semantic-version==2.10.0
      - shapely==2.0.3
      - sniffio==1.3.0
      - statsmodels==0.14.2
      - tensorboard-data-server==0.7.2
      - timm==0.6.12
      - torchdata==0.6.0
      - torchmetrics==1.0.1
      - typing==3.7.4.3
      - typing-extensions==4.8.0
      - uvicorn==0.23.2
      - visdom==0.2.4
      - websocket-client==1.7.0
      - websockets==11.0.3
      - werkzeug==3.0.2
      - yarl==1.9.2
prefix: /home/mahirwar/miniconda3/envs/kfold_amy_plaque1
