name: amy_plague
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.3.2=h166bdaf_0
  - atk-1.0=2.36.0=h28cd5cc_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - blas=1.0=mkl
  - boost-cpp=1.74.0=h312852a_4
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cairo=1.16.0=hf32fb01_1
  - certifi=2022.6.15=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - cfitsio=3.470=h5893167_7
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=10.2.89=h713d32c_10
  - cudnn=7.6.5.32=h01f27c4_1
  - curl=7.82.0=h7f8727e_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.32=py38h6a678d5_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2022.5.0=py38h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.3.2=hca11adc_0
  - fftw=3.3.10=nompi_h77c792f_102
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - freexl=1.0.6=h7f98852_0
  - fribidi=1.0.10=h7b6447c_0
  - fsspec=2022.3.0=py38h06a4308_0
  - future=0.18.2=py38_1
  - gcc=11.2.0=h702ea55_10
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=h4f31c25_6
  - gettext=0.21.0=hf68c758_0
  - ghostscript=9.54.0=h27087fc_2
  - giflib=5.2.1=h7b6447c_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.18=pyhd3eb1b0_1
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.68.0=py38h2109141_1
  - grad-cam=1.3.9=pyhd8ed1ab_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.49.0=h85b4f2f_0
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - gstreamer-orc=0.4.32=h7f98852_1
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - harfbuzz=2.9.1=h83ec7ef_1
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h2531618_0
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagemagick=7.1.0_8=pl5321hb118871_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jasper=1.900.1=hd497a04_4
  - jbig=2.1=hdba287a_0
  - jpeg=9e=h7f8727e_0
  - json-c=0.15=h98cffda_0
  - kealib=1.4.14=hcc255d8_2
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - kiwisolver=1.4.2=py38h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h2531618_0
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.82.0=h0b77cf5_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.7=h27cfd23_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libexif=0.6.21=h7f98852_0
  - libffi=3.3=he6710b0_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libgdal=3.2.2=h358be1b_9
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.2.0=h1234567_1
  - libgsf=1.14.47=h88be47d_4
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=h3826bc1_1
  - libmatio=1.5.21=h9e294dc_0
  - libnetcdf=4.8.1=nompi_hcd642e3_100
  - libnghttp2=1.46.0=hce63b2e_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.5=h27cfd23_1
  - libopencv=4.5.3=py38h5627943_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.16.0=h780b84a_0
  - librsvg=2.52.2=hc3c00ef_0
  - librttopo=1.1.0=h1185371_6
  - libspatialite=5.0.1=h8694cbe_6
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.3.0=hf544144_1
  - libtool=2.4.6=h295c915_1008
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libvips=8.11.4=h0632ac6_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_1
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.3=h295c915_1
  - magma=2.5.4=h5da55e3_2
  - matplotlib=3.5.2=py38h578d9bd_0
  - matplotlib-base=3.5.2=py38h826bfd8_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nccl=2.12.12.1=h1a5f58c_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.7.1=pyhd3eb1b0_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.3=py38h807cd23_0
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - opencv=4.5.3=py38h578d9bd_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openslide=3.4.1=h978ee9a_4
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.4=py38h6a678d5_0
  - pango=1.48.10=hb8ff022_1
  - partd=1.2.0=pyhd3eb1b0_1
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - perl=5.32.1=2_h7f98852_perl5
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=21.2.4=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkg-config=0.29.2=h1bed415_8
  - poppler=21.09.0=h0e1ea10_2
  - poppler-data=0.4.11=h06a4308_0
  - postgresql=13.3=h2510834_0
  - proj=8.0.1=h277dcde_0
  - promise=2.3=py38h06a4308_0
  - protobuf=3.16.0=py38h709712a_0
  - psutil=5.9.0=py38h5eee18b_0
  - py-opencv=4.5.3=py38he5a9106_1
  - pycocotools=2.0.4=py38h6c62de6_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyfiglet=0.8.post1=py_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.12.3=py38ha8c2ead_4
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=cuda102py38hf03d9dd_1
  - pytorch-gpu=1.9.0=cuda102py38hf05f184_1
  - pytz=2022.1=py38h06a4308_0
  - pyvips=2.1.15=py38h497a2fe_0
  - pywavelets=1.3.0=py38h7f8727e_0
  - pyyaml=6.0=py38h7f8727e_1
  - qt=5.12.9=hda022c4_4
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.0=py38h06a4308_0
  - scikit-image=0.19.2=py38h43a58ef_0
  - scipy=1.9.3=py38h14f4228_0
  - sentry-sdk=1.9.0=py38h06a4308_0
  - setproctitle=1.2.2=py38h27cfd23_1004
  - setuptools=61.2.0=py38h06a4308_0
  - shortuuid=1.0.10=pyha770c72_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h9b69904_2
  - smmap=4.0.0=pyhd3eb1b0_0
  - sqlite=3.38.5=hc218d9a_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tifffile=2020.10.1=py38hdd07704_2
  - tiledb=2.3.4=he87e0bf_0
  - timm=0.4.12=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchvision=0.10.0=py38cuda102h1e64cea_0_cuda
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.64.0=py38h06a4308_0
  - ttach=0.0.3=pyhd8ed1ab_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzcode=2022a=h166bdaf_0
  - tzdata=2022a=h191b570_0
  - urllib3=1.26.9=py38h06a4308_0
  - wandb=0.13.5=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - xerces-c=3.2.3=h9d8b166_3
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - joblib==1.2.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - scikit-learn==1.1.3
    - threadpoolctl==3.1.0
prefix: /home/mahirwar/anaconda3/envs/amy_plague
