wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1660931906
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      4: 3.7.11
      5: 0.12.16
      8:
      - 5
batch_size:
  desc: null
  value: 12
detection_threshold:
  desc: null
  value: 0.75
gamma:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
num_epochs:
  desc: null
  value: 10
step_size:
  desc: null
  value: 3
weight_decay:
  desc: null
  value: 0.0005
